name: Generate Daily Horoscope

on:
  schedule:
    # 每天 UTC 时间 00:00 (北京时间 08:00) 运行
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Generate daily horoscope data
      run: node scripts/generate-daily-page.js
    
    - name: Build project
      run: npm run build
      env:
        REACT_APP_SITE_URL: https://dailyhoroscopetoday.org
    
    - name: Update sitemap
      run: node scripts/update-sitemap.js
    
    - name: Commit and push changes
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # 检查是否有更改
          if [ -n "$(git status --porcelain)" ]; then
            echo "Found changes, committing..."
            git add .
            git commit -m "Update daily horoscope data for $(date +'%Y-%m-%d')"
          else
            echo "No changes to commit"
          fi
          
          # 拉取最新更改
          echo "Pulling latest changes..."
          git pull origin main --rebase || git pull origin main
          
          # 推送更改
          echo "Pushing changes..."
          git push origin main


permissions:
  contents: write
  pages: write

  id-token: write
